baseURL = "https://anthonydellavecchia.com/"
languageCode = "en-us"
relativeurls = false
uglyurls = false

paginate = 6
theme = "portio"
title = "Anthony Dellavecchia | Software Engineer"

# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1

[[menu.main]]
name = "About"
url = "about"
weight = 2

[[menu.main]]
name = "Blog"
url = "blog"
weight = 3

[[menu.main]]
name = "Portfolio"
url = "portfolio"
weight = 4

[params]
homeURL = "https://anthonydellavecchia.com/#home"
aboutPageURL = "about"
blogPageURL = "blog"
contactLink = "contact"
homePageURL = "home"
workPageURL = "portfolio"
copyright = "• Made with ❤️, Hugo, & Firebase by Anthony Dellavecchia"
footerLogo = "images/contact/avatar.png"
formspreeURL = "https://formspree.io/f/mvodlbrv"
googleAnalytics = "G-X3SHCY6M34"
logo = "images/contact/avatar.png"
bubbleImg = "images/contact/bubble.png"

[params.address]
address = "Dallas, Texas, USA"
email = "anthony.dellavecchia.tech@gmail.com"
openingHours = """
Mon-Thu 
(2PM-6PM)
"""
phone = "(940) 242 1288"

[params.map]
APIkey = "AIzaSyDGIkGQZO9Pz2MpLwaKKS1yq_7LXZQPd3Q"
latitude = "32.965557"
longitude = "-96.715836"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-github"
url = "https://github.com/anthonyjdella"
weight = 1
[[params.social]]
icon = "fa-linkedin"
url = "https://www.linkedin.com/in/anthonydellavecchia"
weight = 2
[[params.social]]
icon = "fa-medium"
url = "https://medium.com/@anthonyjdella"
weight = 3
[[params.social]]
icon = "fa-file-code-o"
url = "https://dev.to/anthonyjdella"
weight = 4
[[params.social]]
icon = "fa-twitter"
url = "https://twitter.com/anthonyjdella"
weight = 5
[[params.social]]
icon = "fa-instagram"
url = "https://www.instagram.com/anthonyjdella/"
weight = 6
[[params.social]]
icon = "fa-envelope"
url = "mailto:anthony.dellavecchia.tech@gmail.com"
weight = 7
[[params.social]]
icon = "fa-calendar"
url = "https://calendly.com/anthonyjdella"
weight = 8
