baseURL = "https://anthonyjdella.github.io/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "PortAnthony Dellavecchia | Software Developerio"

# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1

[[menu.main]]
name = "About"
url = "#about"
weight = 2

[[menu.main]]
name = "Resume"
url = "#resume"
weight = 3

[[menu.main]]
name = "Service"
url = "#service"
weight = 4

[[menu.main]]
name = "Blog"
url = "#blog"
weight = 5

[[menu.main]]
name = "Work"
url = "#portfolio"
weight = 6

[[menu.main]]
name = "Contact"
url = "#contact"
weight = 7

# Sitemap Menu
[[menu.sitemap]]
name = "About me"
url = "about"
weight = 1
[[menu.sitemap]]
name = "Frequently Ask Question"
url = "#"
weight = 2
[[menu.sitemap]]
name = "Privacy & Policy"
url = "#"
weight = 3
[[menu.sitemap]]
name = "Latest Article"
url = "#"
weight = 4

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "© 2021 • Made with ❤️, Hugo, & Netlify by Anthony Dellavecchia"
footerLogo = "images/contact/avatar.png"
formspreeURL = "https://formspree.io/f/mvodlbrv"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/contact/avatar.png"

[params.address]
address = "Dallas, Texas, USA"
email = "anthony.dellavecchia.tech@gmail.com"
openingHours = """
Mon - Fri  
1pm to 6pm
"""
phone = "(940) 242 1288"

[params.map]
APIkey = "AIzaSyDGIkGQZO9Pz2MpLwaKKS1yq_7LXZQPd3Q"
latitude = "32.965557"
longitude = "-96.715836"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-github"
url = "https://github.com/anthonyjdella"
weight = 1
[[params.social]]
icon = "fa-linkedin"
url = "https://www.linkedin.com/in/anthonydellavecchia"
weight = 2
[[params.social]]
icon = "fa-medium"
url = "https://medium.com/@anthonyjdella"
weight = 3
[[params.social]]
icon = "fa-twitter"
url = "https://twitter.com/anthonyjdella"
weight = 4
[[params.social]]
icon = "fa-instagram"
url = "https://www.instagram.com/anthonyjdella/"
weight = 5
[[params.social]]
icon = "fa-envelope"
url = "mailto:anthony.dellavecchia.tech@gmail.com"
weight = 6